"""add_colunas_criado_em_atualizado_em

Revision ID: d333771b2503
Revises: 1c0719b85d86
Create Date: 2024-09-21 09:46:55.911322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd333771b2503'
down_revision: Union[str, None] = '1c0719b85d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_usuarios', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tb_usuarios', sa.Column('atualizado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_usuarios', 'atualizado_em')
    op.drop_column('tb_usuarios', 'criado_em')
    # ### end Alembic commands ###
