# Generated by Django 5.1.1 on 2024-10-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'verbose_name_plural': 'opções'},
        ),
    ]
