# Generated by Django 5.1.2 on 2024-11-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
